rapidsms/contrib/httptester/urls.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4


from django.conf.urls import url
from . import views


urlpatterns = (
    url(r"^$", views.generate_identity, name='httptester-index'),
    url(r"^(?P<identity>\d+)/$", views.message_tester, name='httptester')
)

rapidsms/contrib/httptester/models.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4

rapidsms/contrib/httptester/forms.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4


from django import forms


# the built-in FileField doesn't specify the 'size' attribute, so the
# widget is rendered at its default width -- which is too wide for our
# form. this is a little hack to shrink the field.
from django.core.exceptions import ValidationError


class SmallFileField(forms.FileField):
    def widget_attrs(self, widget):
        return {"size": 10}


class MessageForm(forms.Form):
    identity = forms.CharField(
        label="Phone Number",
        max_length=100,
        help_text="The phone number which this message " +
                  "will appear to have originated from.")

    text = forms.CharField(
        label="Single Message",
        required=False,
        widget=forms.widgets.Textarea({
            "cols": 30,
            "rows": 4}))

    bulk = SmallFileField(
        label="Multiple Messages",
        required=False,
        help_text="Alternatively, upload a <em>plain text file</em> " +
                  "containing a single message per line.")

    def clean_identity(self):
        if 'identity' in self.cleaned_data:
            identity = self.cleaned_data['identity'].strip()
            if not identity.isnumeric():
                raise ValidationError("Phone number must be all numeric")
            return identity

rapidsms/contrib/httptester/views.py
#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4


from random import randint
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from django_tables2 import RequestConfig

from rapidsms import settings
from . import forms
from . import storage
from .tables import MessageTable


@login_required
def generate_identity(request):
    """Simple view to generate a random identity.

    Just generates a random phone number and redirects to the
    message_tester view.

    :param request: HTTP request
    :return: An HTTPResponse
    """
    return redirect("httptester", randint(111111, 999999))


@login_required
def message_tester(request, identity):
    """The main Message Tester view.

    GET: will display the form, with the default phone number filled
    in from `identity`.

    POST: will process the form and handle it. In this case the identity
    passed to the view is ignored; the identity in the form is used to
    send any messages.

    :param request: HTTP request
    :param identity: Phone number the message will be sent from
    :return: An HTTPResponse
    """
    if request.method == "POST":
        form = forms.MessageForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            identity = cd["identity"]
            if 'clear-all-btn' in request.POST:
                storage.clear_all_messages()
                messages.add_message(request, messages.INFO, "Cleared all messages")
            elif 'clear-btn' in request.POST:
                storage.clear_messages(identity)
                messages.add_message(request, messages.INFO, "Cleared %s messages" % identity)
            else:
                if "bulk" in request.FILES:
                    for line in request.FILES["bulk"]:
                        line = line.decode('utf-8').rstrip("\n")
                        storage.store_and_queue(identity, line)
                    messages.add_message(request, messages.INFO, "Sent bulk messages")
                # no bulk file was submitted, so use the "single message"
                # field. this may be empty, which is fine, since contactcs
                # can (and will) submit empty sms, too.
                else:
                    storage.store_and_queue(identity, cd["text"])
                    messages.add_message(request, messages.INFO, "Sent message")
            url = reverse(message_tester, args=[identity])
            return HttpResponseRedirect(url)

    else:
        form = forms.MessageForm({"identity": identity})

    messages_table = MessageTable(storage.get_messages(),
                                  template_name="httptester/table.html")
    RequestConfig(request,
                  paginate={"per_page": settings.PAGINATOR_OBJECTS_PER_PAGE})\
        .configure(messages_table)

    context = {
        "router_available": True,
        "message_form": form,
        'messages_table': messages_table,
    }
    return render(request, "httptester/index.html", context)

rapidsms/contrib/httptester/templates/httptester/index.html
{% extends "base.html" %}
{% load forms_tags %}
{% load django_tables2 %}

{% block title %}Message Tester - {{ block.super }}{% endblock %}

{% block extra_javascript %}
<script type="text/javascript">
	(function($) {
		$(function() {
			$("#id_text").keypress(function(ev) {
				if (ev.keyCode == 13 && !ev.shiftKey) {
					$(this).closest("form").submit();
					$("#id_submit").focus();
					ev.preventDefault();
				}
			}).focus();
		});
	})(jQuery);
</script>
{% endblock %}

{% block extra_stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}httptester/stylesheets/httptester.css" />
{% endblock %}


{% block content %}
    <div class="page-header">
        <h1>Message Tester</h1>
    </div>

    <div>  {# this div keeps the next two side-by-side #}
        <div class="span4">
            <div>{# <-- without this div, the header overlays the top border of the form area #}
                <form action="" method="post" enctype="multipart/form-data">
                    {% render_form message_form %}
                    {% csrf_token %}

                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" id="send-btn" name="send-btn">Send</button>
                        <label for="send-btn">Send single or multiple messages</label>
                        <button type="submit" class="btn btn-primary" id="clear-btn" name="clear-btn">Clear</button>
                        <label for="clear-btn">Clear saved messages to/from this phone number</label>
                        <button type="submit" class="btn btn-primary" id="clear-all-btn" name="clear-all-btn">Clear all</button>
                        <label for="clear-all-btn">Clear all saved messages</label>
                    </div>
                </form>
            </div>
        </div>
        <div class="span8">
            {% if messages_table.rows %}
                {% render_table messages_table %}
            {% else %}
                <table>
                {% if router_available %}
                    <tr class="no-data look-left">
                        <td colspan="2">
                            <p>
                                You haven't sent or received any test messages yet.<br />
                                Use the form on the left to get started.
                            </p>
                        </td>
                    </tr>{% else %}
                    <tr class="no-data error">
                        <td colspan="2">
                            <p>
                                The RapidSMS router could not be reached.<br />
                                Please check that it is running.
                            </p>
                        </td>
                    </tr>{% endif %}
                </table>
            {% endif %}
        </div>

    </div>
{% endblock %}

rapidsms/contrib/httptester/templates/httptester/table.html
{% extends 'django_tables2/bootstrap-tables.html' %}

{% block table.tbody.row %}
    <tr class="{% if row.record.direction == record.INCOMING %}in{% endif %}">
        {% for column, cell in row.items %}
            <td {{ column.attrs.td.as_html }}>{{ cell }} </td>
        {% endfor %}
    </tr>
{% endblock table.tbody.row %}